"""Time-interleaved ADC model and analysis (Phase 1.1)."""

from ti_adc.analysis import (
    TiDynamicReport,
    TiSpurTone,
    analyze_ti_spurs,
    compute_ti_dynamic_metrics,
    compute_ti_inl_dnl,
    format_ti_dynamic_summary,
    format_ti_static_summary,
    plot_ti_inl_dnl,
    plot_ti_spectrum,
)
from ti_adc.config import (
    DEFAULT_BITS,
    DEFAULT_FS_HZ,
    TiAdcConfig,
    default_noise,
    ideal_noise,
    preset_mismatch_corrected,
    preset_combined_impaired,
    preset_gain_mismatch,
    preset_ideal,
    preset_offset_mismatch,
    preset_skew_mismatch,
    staggered_mismatch,
    uniform_mismatch,
)
from ti_adc.mismatch import (
    ChannelMismatchSample,
    DriftWaveform,
    MismatchKind,
    MismatchProfile,
    effective_mismatch,
    preset_slow_drift,
    preset_static_profile,
    preset_step_drift,
)
from ti_adc.ngspice_engine import (
    read_ti_ngspice_wrdata,
    render_ti_dynamic_netlist,
    render_ti_static_netlist,
    run_ti_ngspice_testbench,
)
from ti_adc.spectre_engine import render_ti_spectre_netlist, run_ti_spectre_testbench
from ti_adc.ti_io import prepare_ti_ngspice_waveform, prepare_ti_spectre_waveform
from ti_adc.ti_model import simulate_ti_dynamic, simulate_ti_static

__all__ = [
    "ChannelMismatchSample",
    "DriftWaveform",
    "MismatchKind",
    "MismatchProfile",
    "DEFAULT_BITS",
    "DEFAULT_FS_HZ",
    "TiAdcConfig",
    "TiDynamicReport",
    "TiSpurTone",
    "analyze_ti_spurs",
    "compute_ti_dynamic_metrics",
    "compute_ti_inl_dnl",
    "default_noise",
    "effective_mismatch",
    "format_ti_dynamic_summary",
    "format_ti_static_summary",
    "ideal_noise",
    "plot_ti_inl_dnl",
    "plot_ti_spectrum",
    "prepare_ti_ngspice_waveform",
    "prepare_ti_spectre_waveform",
    "read_ti_ngspice_wrdata",
    "render_ti_dynamic_netlist",
    "render_ti_spectre_netlist",
    "render_ti_static_netlist",
    "run_ti_ngspice_testbench",
    "run_ti_spectre_testbench",
    "preset_mismatch_corrected",
    "preset_combined_impaired",
    "preset_gain_mismatch",
    "preset_ideal",
    "preset_offset_mismatch",
    "preset_skew_mismatch",
    "preset_slow_drift",
    "preset_static_profile",
    "preset_step_drift",
    "simulate_ti_dynamic",
    "simulate_ti_static",
    "staggered_mismatch",
    "uniform_mismatch",
]
